apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sn360-es.fullname" . }}
  labels:
    {{- include "sn360-es.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sn360-es.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
  template:
    metadata:
      labels:
        {{- include "sn360-es.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- range $k, $v := .Values.podAnnotations }}
        {{ $k }}: {{ tpl ($v | toString) $ | quote }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "sn360-es.serviceAccountName" . }}
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: sn360-es
          image: "{{ include "sn360-es.image" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "sn360-es.fullname" . }}
            {{- if .Values.secret.create }}
            - secretRef:
                name: {{ include "sn360-es.fullname" . }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir:
            sizeLimit: 64Mi
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or .Values.affinity (and .Values.podHA .Values.podHA.enabled) }}
      affinity:
        {{- with .Values.affinity }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if and .Values.podHA .Values.podHA.enabled }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: {{ .Values.podHA.podAntiAffinity.weight }}
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    {{- include "sn360-es.selectorLabels" . | nindent 20 }}
                topologyKey: {{ .Values.podHA.podAntiAffinity.topologyKey }}
        {{- end }}
      {{- end }}
      {{- if or .Values.topologySpreadConstraints (and .Values.podHA .Values.podHA.enabled) }}
      topologySpreadConstraints:
        {{- with .Values.topologySpreadConstraints }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if and .Values.podHA .Values.podHA.enabled }}
        - maxSkew: {{ .Values.podHA.topologySpread.maxSkew }}
          topologyKey: {{ .Values.podHA.topologySpread.topologyKey }}
          whenUnsatisfiable: {{ .Values.podHA.topologySpread.whenUnsatisfiable }}
          labelSelector:
            matchLabels:
              {{- include "sn360-es.selectorLabels" . | nindent 14 }}
        {{- end }}
      {{- end }}
