{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sn360-es.fullname" . }}
  labels:
    {{- include "sn360-es.labels" . | nindent 4 }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  PG_PASSWORD: {{ .Values.secret.data.pgPassword | default "" | quote }}
  REDIS_PASSWORD: {{ .Values.secret.data.redisPassword | default "" | quote }}
  ACTION_TOKEN_HMAC_KEY: {{ .Values.secret.data.jwtSigningKey | default "" | quote }}
  KMS_KEY_ARN: {{ .Values.secret.data.kmsKeyArn | default "" | quote }}
{{- end }}
